verbose: true
logging: true
save: false
baseline: true
max_defence_rounds: 0
max_attack_rounds: 4
min_performance_percentage_attack: 0.5
min_performance_percentage_defence: 0.8
min_safety_percentage: 0.8
avg_multiple_vaccines: false
# save_immunised: true