verbose: true
logging: true
torch_seed: 3
save: true
min_performance_percentage_attack: 0.2
min_performance_percentage_defence: 0.5
min_safety_percentage: 0.8
init_defence_epochs: 150
init_defence_batch_size: 16
init_defence_prompts: 520
max_defence_rounds: 3
max_attack_rounds: 3
max_immunization_rounds: 4
tqdm: true