model_name_or_path: /home/jovyan/.cache/huggingface/hub/Llama-3-8b_CB
verbose: true
logging: true
save: false
baseline: true
memory_less: true
max_defence_rounds: 0
max_attack_rounds: 4
run_name: cb_benchmark
min_performance_percentage_attack: 0.2