lora_adaptor: /home/jovyan/.cache/huggingface/hub/repnoise/Meta-Llama-3-8B-Instruct_repnoise_0.1_0.001_20
verbose: true
logging: true
torch_seed: 33
save: false
baseline: true
max_defence_rounds: 0
max_attack_rounds: 4
min_performance_percentage_attack: 0.2
min_performance_percentage_defence: 0.5
min_safety_percentage: 0.8
avg_multiple_vaccines: false
# save_immunised: true
mount_vaccines: et_repnoise*
run_name: et_repnoise_benchmark_33