lora_adaptor: /home/jovyan/.cache/huggingface/hub/tar/Meta-Llama-3-8B-Instruct_tar_20
verbose: true
logging: true
torch_seed: 33
save: true
min_performance_percentage_attack: 0.2
min_performance_percentage_defence: 0.5
min_safety_percentage: 0.8
init_defence_epochs: 150
init_defence_batch_size: 16
init_defence_prompts: 520
max_defence_rounds: 3
max_attack_rounds: 4
max_immunization_rounds: 5
tqdm: true
run_name: et_tar