lora_adaptor: /home/jovyan/.cache/huggingface/hub/t_vaccine/Meta-Llama-3-8B-Instruct_TVaccine_3_8_20_200_200_20
verbose: true
logging: true
save: true
min_performance_percentage_attack: 0.5
min_performance_percentage_defence: 0.8
min_safety_percentage: 0.8
init_defence_epochs: 50
max_immunization_rounds: 8
max_defence_rounds: 4
max_attack_rounds: 3
run_name: et_t_vac