# config/debug.yaml

model_name_or_path: google/gemma-2-2b-it
eval_model: meta-llama/Llama-Guard-3-1B
verbose : true 
init_attack_prompts: 10
init_defence_prompts: 20
init_eval_safety_prompts: 2
init_eval_performance_prompts: 2
performance_batches: 2
multiblock_defences: true
min_toxicity_increase_factor: 0.0
min_performance_percentage_attack: 0.0