verbose: true
logging: true
torch_seed: 3
save: true
min_performance_percentage_defence: 0.7
min_performance_percentage_attack: 0.2
init_attack_intervention_places: block
init_defence_epochs: 50
max_immunization_rounds: 4
run_name: low_reg
defence_reg_coeff: 0.05