verbose: true
logging: true
torch_seed: 33
save: true
min_performance_percentage_attack: 0.2
min_performance_percentage_defence: 0.01
min_safety_percentage: 0.88
init_defence_epochs: 150
init_defence_batch_size: 16
init_defence_prompts: 520
performance_batches: 10
max_defence_rounds: 3
max_attack_rounds: 4
max_immunization_rounds: 5
tqdm: true
run_name: no_perf